# PostgreSQL Configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/incentivos_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.parameter-names-module.mode=OVERRIDE

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true

springdoc.api-docs.version=openapi_3_0

# Server Configuration for Dockerfile
server.port=${PORT:8080}

#Apis Externas
url.donadores = ${URL_DONADORES:https://donadores-y-entidades-0uv4.onrender.com}